server {
    listen 6173 ssl;
    server_name goldenticket.lat;

    ssl_certificate     /etc/nginx/ssl/goldenticket.lat/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/goldenticket.lat/privkey.key;

    root /var/www/arranhacel;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
